name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.86, stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Show Rust version
        run: |
          rustc --version
          cargo --version

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check dependency sorting
        run: |
          # Install cargo-sort if not available
          if ! command -v cargo-sort &> /dev/null; then
            cargo install cargo-sort
          fi
          cargo sort --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Run integration tests
        run: cargo test --test integration --verbose

      - name: Check build
        run: cargo check --all-features

      - name: Build release
        run: cargo build --release

      - name: Check binary size
        run: |
          echo "Binary size:"
          ls -lh target/release/uniswap_relay

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: |
          cargo install cargo-audit --version 0.21.2

      - name: Run security audit
        run: cargo audit

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-tarpaulin
        run: |
          cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml --output-dir coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/cobertura.xml
          flags: unix
          name: codecov-umbrella
          fail_ci_if_error: false

  dependency-updates:
    name: Check for Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-outdated
        run: |
          cargo install cargo-outdated

      - name: Check for outdated dependencies
        run: |
          echo "Checking for outdated dependencies (informational only)..."
          cargo outdated || echo "No outdated dependencies found or cargo-outdated check completed"
          # Note: This check is informational and won't fail the CI pipeline

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t uniswap-relay:test .

      - name: Test Docker image
        run: |
          docker run --rm uniswap-relay:test --help || true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-sort
        run: |
          cargo install cargo-sort

      - name: Check Cargo.toml sorting
        run: cargo sort --check

      - name: Check for TODO/FIXME comments
        if: false
        run: |
          if grep -r "TODO\|FIXME" src/ --include="*.rs"; then
            echo "Found TODO/FIXME comments. Please address them before merging."
            exit 1
          fi

      - name: Check for debug prints
        if: false 
        run: |
          if grep -r "println!\|dbg!" src/ --include="*.rs"; then
            echo "Found debug prints. Please remove them before merging."
            exit 1
          fi 